unique_ids:
  assets:
    standard-page.html: KMUZWBZDIZAXNAP6ENL62SSKMSVHUSX5
    theme.css: PE2C7RQYAHU776G6PLACXV4QMVD2WLSY
  forms:
    Form1: 53QWOWT3DZH2ACHKWU2OPHAPZZFNXDLW
  modules: {}
  scripts: {}
  server_modules: {}
